routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/page', 'PageController')->except(['show']);
    Route::resource('/ruang_tengah', 'RuangTengahController')->except(['show']);
    Route::resource('/user', 'UserController');
});

Route::get('/ruang_tengah', 'RuangTengahController@front')->name('ruang_tengah.front');
Route::post('/ruang_tengah/register', 'RuangTengahController@register')->name('ruang_tengah.register');

Route::post('/user/get_notified', 'UserController@SignUpNotification')->name('user.sign_up_notification');

Route::get('/{page}', 'PageController@show')->name('page.show');

app/Page.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','organization','membership','notification'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PageController.php
<?php

namespace App\Http\Controllers;

use App\Page;
use Illuminate\Http\Request;

class PageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function show(Page $page)
    {
        return view('home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function edit(Page $page)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Page $page)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function destroy(Page $page)
    {
        //
    }
}

app/Http/Controllers/RuangTengahController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;

class RuangTengahController extends Controller
{
    /**
     * Show Ruang Tengah Front Page.
     *
     * @param  \App\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function front()
    {
        return view('pages.ruang_tengah.front');
    }

    /**
     * Register ruang tengah participants.
     *
     * @param  \App\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function register(Request $request)
    {

        $request->validate([

            'name' => 'required',
            'email' => 'required|email',
            'organization' => 'required'
        ]);

        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'organization' => $request->organization,
            'membership' => $request->membership,
            'password' => bcrypt('tipolmember')
        ]);

        $flash_data = array(
            'alert' => array(
              'type' => 'success',
              'message' => 'Thank you for registering. We will notify you future Ruang Tengah sessions.'
            )
          );

        return redirect()->route('ruang_tengah.front')->with('fdata', $flash_data);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = User::all();

        return view('pages.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }


    /**
     * Handle email registration to get notified.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function SignUpNotification(Request $request)
    {

        $request->validate([
            'email' => 'required|email',
        ]);

        User::create([
            'email' => $request->email,
            'password' => bcrypt('registernotification'),
        ]);

        $flash_data = array(
            'alert' => array(
              'type' => 'success',
              'message' => 'Thank you for registering. You will receive updates about our program.'
            )
          );

        return redirect('/')->with('fdata', $flash_data);

    }
}

resources/views/home.blade.php
@extends('layouts.front')

@section('title')
Welcome
@endsection

@section('content')
<div class="container-fluid" id="front">
    <div class="row">
        <div class="col-md-8" class="welcome-hero">

        </div>
    </div>
    <div class="row">
        <div class="col text-center">
        <img class="logo-center" src=" {{ asset('img/TPS_logo_light.png') }}"/>

        <h3>We are a network of young professionals<br />
        That promotes a mindset for policy analysis and design<br />
        Based on evidence and empathy</h3>

        <p class="mt-4">Register your email below to get notified of our programs.</p>

        <form method="POST" action="{{ route('user.sign_up_notification') }}">
            @csrf

            <div class="form-group row">

                <div class="col-md-4 offset-md-4">
                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                    @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>

            <div class="form-group row mb-0">
                <div class="col-md-2 offset-md-5">
                    <button type="submit" class="btn btn-white">
                        Register
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@section('js')
@endsection

@section('css')
<style>
.logo-center {
    width:250px;
}

body {
    background-image: url('{{ asset('img/bg_front1.png')}}');
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}

body h1,
body h2,
body h3,
body h4,
body h5,
body h6,
body p {

}

body a {
    color: #ccc;
}

.nav-link {
    color: white;
}

.btn-white {
    background-color: white;
    color: #444;
}


</style>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'ThinkPolicy') }} | @yield('title')</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <link rel="shortcut icon" href=" {{ asset('img/favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ asset('img/favicon.ico') }}" type="image/x-icon">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('css')
</head>
<body>
    <div id="app">

        @include('shared.navbar')

        <!-- Flash data -->
        @if(session('fdata') !== null)
            @include('shared.alert')
        @endif

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
<!-- Scripts -->
<script src="{{ asset('js/manifest.js') }}"></script>
<script src="{{ asset('js/vendor.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>
@yield('js')
</html>

resources/views/layouts/front.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'ThinkPolicy') }} | @yield('title')</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <link rel="shortcut icon" href=" {{ asset('img/favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ asset('img/favicon.ico') }}" type="image/x-icon">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('css')
</head>
<body>
    <div id="app">

        @include('shared.navbar')

        <!-- Flash data -->
        @if(session('fdata') !== null)
            @include('shared.alert')
        @endif

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
<!-- Scripts -->
<script src="{{ asset('js/manifest.js') }}"></script>
<script src="{{ asset('js/vendor.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>
@yield('js')
</html>

resources/views/pages/ruang_tengah/front.blade.php
@extends('layouts.front')

@section('title')
Ruang Tengah
@endsection

@section('content')
<div class="container">
    <div class="row my-4">
        <div class="col">
            <h4>Ruang tengah is a safe space to discuss ideas, without strings attached.</h4>
            <p class="mt-4 mb-0">Register below to get news of the next Ruang Tengah.</p>
        </div>
    </div>
</div>

<div class="container" id="front">
    <div class="row">
        <div class="col">

        </div>
    </div>
    <div class="row">
        <div class="col-md-8">

            <form method="POST" action="{{ route('ruang_tengah.register') }}">
                @csrf

                <div class="form-group row">
                    <label for="name" class="col-md-2 col-form-label text-md-right">Name</label>

                    <div class="col-md-5">
                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="email" class="col-md-2 col-form-label text-md-right">{{'E-Mail'}}</label>

                    <div class="col-md-5">
                        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                        @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="organization" class="col-md-2 col-form-label text-md-right">Organization</label>

                    <div class="col-md-5">
                        <input id="organization" type="text" class="form-control @error('organization') is-invalid @enderror" name="organization" value="{{ old('organization') }}" required>

                        @error('organization')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>


                <div class="form-group row">
                    <label for="membership" class="col-md-5 col-form-label text-md-right">Register for ThinkPolicy membership?</label>

                    <div class="col-md-3">
                        <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="membership" value="1" checked='checked'>
                    <label class="form-check-label" for="inlineRadio1">Yes</label>
                    </div>
                        <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="membership" value="0">
                    <label class="form-check-label" for="inlineRadio2">No</label>
                    </div>

                        @error('organization')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row mb-0">
                    <div class="col-md-2 offset-md-5">
                        <button type="submit" class="btn btn-white">
                            Sign up
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@section('css')
<style>

body {
    background-image : url("{{ asset('img/bg_rute1.png')}}");
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}

body h1,
body h2,
body h3,
body h4,
body h5,
body h6,
body p,
body label {
    color: white;
}

.btn-white {
    background-color: white;
    color: #444;
}

body a {
    color: #ccc;
}


</style>

@endsection

@section('js')
@endsection

resources/views/pages/user/index.blade.php
@extends('layouts.app')

@section('title')
Ruang Tengah
@endsection

@section('content')
<div class="container">
    <h4>User list</h4>
    <div class="row my-4">
        <div class="col">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Organization</th>
                        <th>Member?</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $u)
                    <tr>
                        <td>{{ $u->name }}</td>
                        <td>{{ $u->email }}</td>
                        <td>{{ $u->organization }}</td>
                        <td>
                            @if($u->membership)
                                <span class="badge badge-success">Yes</span>
                            @else
                                <span class="badge badge-danger">No</span>
                            @endif
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endsection

@section('css')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.20/sl-1.3.1/datatables.min.css"/>
@endsection

@section('js')
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/sl-1.3.1/datatables.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('.table').DataTable();
    } );
</script>
@endsection

resources/views/shared/alert.blade.php
<?php
  // Process the data
  $fdata = session('fdata'); // getting $flash_data
  $fdata = $fdata['alert'];
  $type = isset($fdata['type']) ? $fdata['type'] : 'primary';
  $dismissable = isset($fdata['dismissable']) ? $fdata['dismissable'] : true;
  $heading = isset($fdata['heading']) ? $fdata['heading'] : false;
  $message = $fdata['message'];
  $link = isset($fdata['link']) ? $fdata['link'] : false;
?>

<section class="section">
  <div class="container">
    <div class="row"></div class="col">
    <div class="alert alert-{{ $fdata['type'] }}">
      @if($heading) <h4 class="alert-{{ $fdata['type'] }}"> {{ $heading }} </h4> @endif
        <p class="mb-0 alert-{{ $fdata['type'] }}">{{ $message }}</p>
      @if($link)
        <hr/>
        {{ $link }}
      @endif
    </div>
    </div></div>
  </div>
</section>

resources/views/shared/navbar.blade.php
@guest
    @php
        $navbar = "navbar-dark";
        $home_url = '/';
    @endphp
@else
    @php
        $navbar = "navbar-light";
        $home_url = '/home';
    @endphp
@endauth

<nav class="navbar navbar-expand-md {{ $navbar }} shadow-sm">
    <div class="container">

        <a class="navbar-brand " href="{{ url($home_url) }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>


<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <!-- Left Side Of Navbar -->
    @guest
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link " href="{{ route('ruang_tengah.front') }}">Ruang Tengah</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Bootcamp</a>
        </li>

    </ul>

    @endguest

    @auth
   <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a id="navbar" class="nav-link " href="#" role="button" aria-haspopup="true" aria-expanded="false" v-pre>
                Ruang Tengah<span class="caret"></span>
            </a>
        </li>

        <li class="nav-item">
            <a id="navbar" class="nav-link " href="#" role="button" aria-haspopup="true" aria-expanded="false" v-pre>
                Bootcamp<span class="caret"></span>
            </a>
        </li>

        <!--<li class="nav-item dropdown">
            <a id="navbarDropdown" class="nav-link dropdown-toggle " href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                Ruang Tengah<span class="caret"></span>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item " href="{{ route('page.edit', ['page' => 'ruang_tengah.edit']) }}">Edit
            </a>
        </li>


        <li class="nav-item dropdown">
            <a id="navbarDropdown" class="nav-link dropdown-toggle " href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                Academy<span class="caret"></span>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ route('page.edit', ['page' => 'academy']) }}">Edit
            </a>
        </li>

        <li class="nav-item dropdown">
            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                Library<span class="caret"></span>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ route('page.edit', ['page' => 'library']) }}">Edit
            </a>
        </li>-->
    </ul> 
    @endauth

    <!-- Right Side Of Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Authentication Links -->
        @guest
            <li class="nav-item">
                <a class="nav-link " href="{{ route('login') }}">Login</a>
            </li>
            <!-- @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">Signup</a>
                </li>
            @endif -->
        @else
            @if(Auth::user()->id == 1)
            <li class="nav-item">
                <a class="nav-link " href="{{ route('user.index') }}">User List</a>
            </li>
            @endif

            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item " href="#"
                        onclick="event.preventDefault();
                                        document.getElementById('profile-form').submit();">
                        {{ __('Profile') }}
                    </a>
                    <a class="dropdown-item " href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
        @endguest
    </ul>

        </div>
    </div>
</nav>